name: GuyRoyse.com
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true
timezone: America/Detroit
future: false
safe: true
paginate: 5
