name: Guy Royse
description: Work. Life. Code. Game. Lather. Rinse. Repeat.
url: http://guyroyse.com
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sass-converter
  - kramdown
  - rouge
whitelist:
  - jekyll-redirect-from
markdown: kramdown
highlighter: rouge
timezone: America/Detroit
safe: false
paginate: 5
paginate_path: "/blog/page:num/"
